---
title: "Draft Quarto document"
author: "Clemens Wittenebcher"
format: html
execute:
  echo: true
---

---
# YAML header
---

---
editor:
  markdown:
    wrap: 72
    canonical: true
---

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results

## Descriptive statistics table

```{r}
tar_read(df_stats_by_metabolite)
```

```{r}
targets::tar_read(df_stats_by_metabolite) %>% 
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean (SD)` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites.")
```

## Univariate metabolite distributions

```{r}
tar_read(fig_metabolite_distribution)
```

## Building the model

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

```{r setup}
library(tidyverse)
source(here::here("R/functions.R"))
lipidomics <- read_csv(here::here("data/lipidomics.csv"))
```

```{r}
lipidomics_wide <- lipidomics %>%
  column_values_to_snake_case(metabolite) %>% 
    metabolites_to_wider()

```

```{r}
create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"),
  lipidomics_wide %>%
    create_recipe_spec(metabolite_cholesterol)) %>%
  fit(lipidomics_wide) %>%
  tidy_model_output()
```

## Running multiple models

```{r}
model_estimates <- lipidomics %>%
  split_by_metabolite() %>%
  map(generate_model_results) %>%
  list_rbind() %>% 
  filter(str_detect(term, "metabolite_")) 
model_estimates
```

```{r}
lipidomics %>%
  mutate(term = metabolite) %>%
  column_values_to_snake_case(term) %>%
  mutate(term = str_c("metabolite_", term)) %>%
  distinct(term, metabolite) %>%
  right_join(model_estimates, by = "term")
```

